-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE masterdata (
    id character varying(128) PRIMARY KEY,
    timestamp timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    client_id character varying(128) REFERENCES organization_clients(client_id),
    organization_id integer REFERENCES organizations(id) ON DELETE CASCADE,
    source character varying(128) NOT NULL,
    status character varying(40) NOT NULL,
    xml_data text NOT NULL,
    json_data text
);

-- Indices -------------------------------------------------------

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX master_data_pkey ON masterdata(id text_ops);
CREATE INDEX masterdata_organization_id_index ON masterdata(organization_id int4_ops);
CREATE INDEX masterdata_organization_id_timestamp_idx ON masterdata(organization_id int4_ops,timestamp timestamptz_ops);
CREATE INDEX masterdata_organization_id_status_idx ON masterdata(organization_id int4_ops,status text_ops);


CREATE TABLE masterdata_destinations (
    id character varying(128) PRIMARY KEY,
    masterdata_id character varying(128) REFERENCES masterdata(id) ON DELETE CASCADE,
    destination_name character varying(128),
    service_name character varying(128),
    status character varying(128) NOT NULL,
    timestamp timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    blockchain_response text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX masterdata_destinations_pkey ON masterdata_destinations(id text_ops);
