-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE routing_rules (
    id SERIAL PRIMARY KEY,
    organization_id integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    data_field integer NOT NULL REFERENCES routing_rules_data_fields(id) ON DELETE CASCADE,
    comparator integer NOT NULL REFERENCES routing_rules_comparators(id),
    value text NOT NULL,
    destinations json NOT NULL,
    order integer DEFAULT 0,
    status character varying(20) DEFAULT 'ACTIVE'::character varying
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX routing_rules_pkey ON routing_rules(id int4_ops);

-- Table Definition ----------------------------------------------

CREATE TABLE routing_rules_audit_log (
    id SERIAL PRIMARY KEY,
    rules_id integer NOT NULL REFERENCES routing_rules(id),
    timestamp timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    editor character varying(256) NOT NULL,
    organization_id integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    change_description text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX routing_rules_audit_log_pkey ON routing_rules_audit_log(id int4_ops);

-- Table Definition ----------------------------------------------

CREATE TABLE routing_rules_comparators (
    id SERIAL PRIMARY KEY,
    operation text NOT NULL,
    display_name text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX routing_rules_comparators_pkey ON routing_rules_comparators(id int4_ops);


-- Table Definition ----------------------------------------------

CREATE TABLE routing_rules_data_fields (
    id SERIAL PRIMARY KEY,
    path text NOT NULL,
    display_name text NOT NULL,
    value_prefix text,
    event_type text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX routing_rules_data_fields_pkey ON routing_rules_data_fields(id int4_ops);
