-- DDL generated by Postico 1.5.8
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE organizations (
    id SERIAL PRIMARY KEY,
    name character varying(256) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX organizations_pkey ON organizations(id int4_ops);

-- Table Definition ----------------------------------------------

CREATE TABLE organization_clients (
    client_id character varying(128) PRIMARY KEY,
    organization_id integer NOT NULL REFERENCES organizations(id),
    source_name character varying(128) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX organization_tenants_pkey ON organization_clients(client_id text_ops);

-- Table Definition ----------------------------------------------

CREATE TABLE organization_users (
    username character varying(256) PRIMARY KEY,
    organization_id integer NOT NULL REFERENCES organizations(id),
    subject_id character varying(256)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX organization_users_pkey ON organization_users(username text_ops);
